### ISSUE TITLE
Bors stuck in Pending - Running

### ISSUE THREAD

**Issue by jamtur01** [bors-ng/bors-ng#1046]
We have Bors deployed into Heroku (deployed last night so presume latest and greatest). We're using Github Actions for our CI. 

Our problem is when we run `bors r+` it inconsistently executes actions, for example:

https://github.com/timberio/vector/pull/4380

![image](https://user-images.githubusercontent.com/4365/95091228-31aadc00-06f4-11eb-8050-f70ed6ddbf97.png)

But no action is running - https://github.com/timberio/vector/actions

It's been in that state for 2 hours now without initiating an action. The inconsistency - in other PRs we see the yellow "in progress" dot next to the merged commit:

![image](https://user-images.githubusercontent.com/4365/95091499-88181a80-06f4-11eb-962f-3ad935af7b63.png)

And everything works fine.

This is the only log output from Heroku I can see:

```text
2020-10-05T13:59:11.333118+00:00 app[web.1]: 13:59:11.332 pid=<0.6158.0> [error] GenServer #PID<0.6158.0> terminating
2020-10-05T13:59:11.333125+00:00 app[web.1]: ** (MatchError) no match of right hand side value: #PID<0.5950.0>
2020-10-05T13:59:11.333126+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
2020-10-05T13:59:11.333126+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
2020-10-05T13:59:11.333127+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
2020-10-05T13:59:11.333128+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
2020-10-05T13:59:11.333128+00:00 app[web.1]: (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2020-10-05T13:59:11.333130+00:00 app[web.1]: Last message: {:poll, :repeat}
2020-10-05T14:01:02.995471+00:00 app[web.1]: 14:01:02.995 pid=<0.6205.0> [error] GenServer #PID<0.6205.0> terminating
2020-10-05T14:01:02.995482+00:00 app[web.1]: ** (MatchError) no match of right hand side value: #PID<0.5950.0>
2020-10-05T14:01:02.995482+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
2020-10-05T14:01:02.995483+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
2020-10-05T14:01:02.995483+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
2020-10-05T14:01:02.995484+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
2020-10-05T14:01:02.995485+00:00 app[web.1]: (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2020-10-05T14:01:02.995486+00:00 app[web.1]: Last message: {:poll, :repeat}
2020-10-05T14:06:29.385747+00:00 app[web.1]: 14:06:29.384 pid=<0.6232.0> [error] GenServer #PID<0.6232.0> terminating
2020-10-05T14:06:29.385757+00:00 app[web.1]: ** (MatchError) no match of right hand side value: #PID<0.5950.0>
2020-10-05T14:06:29.385757+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
2020-10-05T14:06:29.385758+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
2020-10-05T14:06:29.385758+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
2020-10-05T14:06:29.385762+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
2020-10-05T14:06:29.385762+00:00 app[web.1]: (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2020-10-05T14:06:29.385764+00:00 app[web.1]: Last message: {:poll, :repeat}
2020-10-05T14:06:29.392674+00:00 app[web.1]: 14:06:29.391 pid=<0.6233.0> [error] GenServer #PID<0.6233.0> terminating
2020-10-05T14:06:29.392675+00:00 app[web.1]: ** (MatchError) no match of right hand side value: #PID<0.5950.0>
2020-10-05T14:06:29.392676+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
2020-10-05T14:06:29.392676+00:00 app[web.1]: (bors 0.1.0) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
2020-10-05T14:06:29.392676+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
2020-10-05T14:06:29.392677+00:00 app[web.1]: (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
2020-10-05T14:06:29.392677+00:00 app[web.1]: (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2020-10-05T14:06:29.392678+00:00 app[web.1]: Last message: {:poll, :repeat}
```

**Comment by njasm** [comment]
I'm trying out bors and having the same problem.
