### ISSUE TITLE
Bors waiting for a long time before merging

### ISSUE THREAD

**Issue by TheNeikos** [bors-ng/bors-ng#108]
After bors shows that the build succeeded it takes several minutes for it to be merged. Why is there such a long wait time?

**Comment by TheNeikos** [comment]
As an example: 
![](https://i.imgur.com/rbvEeKI.png)

And its stuck like this for the past 10 minutes at least (first time I checked). Is there anything I could have done wrong in the configuration?

**Comment by notriddle** [comment]
I tried doing it on my test repo, and it affected it, too:

```
2017-03-01T17:31:55.687166+00:00 app[web.1]: 17:31:55.686 [error] GenServer Aelita2.GitHub terminating
2017-03-01T17:31:55.687179+00:00 app[web.1]: ** (HTTPoison.Error) :timeout
2017-03-01T17:31:55.687181+00:00 app[web.1]:     (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
2017-03-01T17:31:55.687182+00:00 app[web.1]:     (aelita2) lib/aelita2/github/server.ex:156: Aelita2.GitHub.Server.do_handle_call/3
2017-03-01T17:31:55.687182+00:00 app[web.1]:     (aelita2) lib/aelita2/github/server.ex:40: Aelita2.GitHub.Server.handle_call/3
2017-03-01T17:31:55.687183+00:00 app[web.1]:     (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
2017-03-01T17:31:55.687184+00:00 app[web.1]:     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2017-03-01T17:31:55.687184+00:00 app[web.1]:     (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
2017-03-01T17:31:55.687185+00:00 app[web.1]: Last message: {:synthesize_commit, {{:installation, 5505}, 68482699}, {%{branch: "staging", commit_message: "Merge #70\n\n70: Delete a\n", parents: ["cb689273eae5bbb59
b079f7bdf2444bb27c54237", "3219bb22f94557395a8aa2efabc1611aa8e919d9"], tree: "c0b7b2a1afb8cea6f2a3dde17368116124125282"}}}
```

I restarted the Heroku dyno, and it worked now. So apparently I was down. Sorry about that.

**Comment by TheNeikos** [comment]
Maybe it had to do with the S3 outage yesterday. Heroku is hosted there AFAIK.
