### ISSUE TITLE
Pushes every hour with [ci skip]

### ISSUE THREAD

**Issue by TheNeikos** [bors-ng/bors-ng#116]
Currently my notifications look like this:

![https://i.imgur.com/yqyFalk.png](https://i.imgur.com/yqyFalk.png)

I don't think that's wanted

**Comment by notriddle** [comment]
There's an error in `merge_branch!`, and it's repeatedly retrying and failing.

```
2017-03-09T17:45:37.928228+00:00 app[web.1]: 17:45:37.928 [error] GenServer #PID<0.485.0> terminating
2017-03-09T17:45:37.928255+00:00 app[web.1]:     (bors_github) lib/github.ex:67: BorsNG.GitHub.merge_branch!/2
2017-03-09T17:45:37.928254+00:00 app[web.1]: ** (MatchError) no match of right hand side value: {:error, :merge_branch}
2017-03-09T17:45:37.928256+00:00 app[web.1]:     (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
2017-03-09T17:45:37.928257+00:00 app[web.1]:     (bors_frontend) lib/bors_ng/batcher.ex:228: BorsNG.Batcher.start_waiting_batch/1
2017-03-09T17:45:37.928258+00:00 app[web.1]:     (bors_frontend) lib/bors_ng/batcher.ex:162: BorsNG.Batcher.poll/1
2017-03-09T17:45:37.928259+00:00 app[web.1]:     (ecto) lib/ecto/adapters/sql.ex:615: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
2017-03-09T17:45:37.928259+00:00 app[web.1]:     (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
2017-03-09T17:45:37.928260+00:00 app[web.1]:     (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
```
