### ISSUE TITLE
Running a docker image fails with "Fatal - Unknown CA"

### ISSUE THREAD

**Issue by jeehoonkang** [bors-ng/bors-ng#1196]
I'm using DockerHub image of `borsng/bors-ng`.  It worked well with a previous image 3 weeks ago, but after upgrading it to [the latest one](https://hub.docker.com/layers/borsng/bors-ng/latest/images/sha256-42598d88d5135784f59b6f5549093457f07a6620fce935ce48e7981dd49ea148?context=explore), it started not working.  Specifically, When running the latest image on a local Docker host, it fails with the following messages:

```
...
web_1       | 18:08:22.413 pid=<0.2118.0> [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA                                                          
web_1       |                                                                                                                                                                                                      
web_1       | 18:08:22.414 pid=<0.2111.0> [error] GET https://api.github.com/app -> error: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - 
Unknown CA\n'}} (21.589 ms)                                                                                                                                                                                        
web_1       | 18:08:22.535 pid=<0.2121.0> [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA
web_1       |                                                                                                                                                                                                      
web_1       | 18:08:22.536 pid=<0.2111.0> [error] GET https://api.github.com/app -> error: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - 
Unknown CA\n'}} (19.837 ms)                                                                              
web_1       | 18:08:22.757 pid=<0.2124.0> [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA
web_1       | 
web_1       | 18:08:22.758 pid=<0.2111.0> [error] GET https://api.github.com/app -> error: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - 
Unknown CA\n'}} (21.104 ms)
web_1       | 18:08:23.178 pid=<0.2127.0> [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA
web_1       |      
web_1       | 18:08:23.178 pid=<0.2111.0> [error] GET https://api.github.com/app -> error: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - 
Unknown CA\n'}} (18.255 ms)  
web_1       | 18:08:23.999 pid=<0.2130.0> [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA
web_1       |                             
web_1       | 18:08:23.999 pid=<0.2111.0> [error] GET https://api.github.com/app -> error: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - 
Unknown CA\n'}} (18.999 ms)    
web_1       | 18:08:25.620 pid=<0.2133.0> [info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA
web_1       |                    
web_1       | 18:08:25.621 pid=<0.2111.0> [error] GET https://api.github.com/app -> error: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - 
Unknown CA\n'}} (19.489 ms)                                                                              
web_1       | 18:08:25.621 pid=<0.2111.0> [error] GenServer BorsNG.GitHub terminating
web_1       | ** (Tesla.Error) {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA\n'}} (GET /app)
web_1       |     (tesla 1.4.0) lib/tesla.ex:318: Tesla.execute!/3
web_1       |     (bors 0.1.0) lib/github/github/server.ex:65: BorsNG.GitHub.Server.handle_call/3
web_1       |     (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
web_1       |     (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
web_1       |     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
web_1       | Last message (from BorsNG.Supervisor): :get_app
web_1       | 18:08:25.623 pid=<0.1873.0> [info] Application bors exited: BorsNG.Application.start(:normal, []) returned an error: shutdown: failed to start child: BorsNG.Attrs
web_1       |     ** (EXIT) exited in: GenServer.call(BorsNG.GitHub, :get_app, 10000)
web_1       |         ** (EXIT) an exception was raised:
web_1       |             ** (Tesla.Error) {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:1887 generated CLIENT ALERT: Fatal - Unknown CA\n'}} (GET /app)
web_1       |                 (tesla 1.4.0) lib/tesla.ex:318: Tesla.execute!/3
web_1       |                 (bors 0.1.0) lib/github/github/server.ex:65: BorsNG.GitHub.Server.handle_call/3
web_1       |                 (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
web_1       |                 (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
web_1       |                 (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I guess it is related to SSL client verification.  I wonder if any of you have experienced the same errors.

**Comment by RetWolf** [comment]
Potentially related to this commit: https://github.com/bors-ng/bors-ng/commit/43a4cb2ada97ff9c7552c3838b4ed46fc9c74d69
Not sure the context around the change

**Comment by notriddle** [comment]
The change was to fix a TLS-related bug that only took place on Heroku. It seems like there are considerable differences between Heroku's runtime and the Debian Buster Docker container...

In any case, I've reproduced the problem and pushed a pull request to fix it. https://github.com/bors-ng/bors-ng/pull/1197
