### ISSUE TITLE
Github API returning 401 "Bad Credentials" error during initial OAuth flow

### ISSUE THREAD

**Issue by RetWolf** [bors-ng/bors-ng#1212]
Currently running into an auth issue with a Bors deployment inside our Github Org. Whenever users try to sign in through the Github authorization flow, they are returned to the /auth/github/callback route and get an internal server error message (500). The 500 appears to be generated on the server due to a 401 Unauthorized response from the Github API. This 401 leads me to believe there's an issue with revoked user tokens as documented here: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#github_app_authorization, but I'm not very familiar with Github auth. 

Here's an example log:
```
23:43:35.476 pid=<0.2113.0> [info] GET https://api.github.com/app -> 200 (198.001 ms)
23:43:35.482 pid=<0.2151.0> [info] Running BorsNG.Endpoint with cowboy 1.1.2 at 0.0.0.0:4000 (http)
23:43:35.483 pid=<0.2097.0> [info] Access BorsNG.Endpoint at https://xxxx.com
23:44:04.302 request_id=d8d61e18c3900ef09c811cc8b12fab9b pid=<0.2288.0> [info] GET /
23:44:04.306 request_id=d8d61e18c3900ef09c811cc8b12fab9b pid=<0.2288.0> [info] Sent 302 in 3ms
23:44:04.375 request_id=d4e4aa4aaae804868039ab9cdae18dc0 pid=<0.2288.0> [info] GET /auth/github
23:44:04.375 request_id=d4e4aa4aaae804868039ab9cdae18dc0 pid=<0.2288.0> [info] Sent 302 in 406µs
23:44:04.673 request_id=ed2bbedf3bbfafa89ec6691235645147 pid=<0.2288.0> [info] GET /auth/github/callback
23:44:04.777 request_id=ed2bbedf3bbfafa89ec6691235645147 pid=<0.2288.0> [info] Sent 500 in 103ms
23:44:04.777 request_id=ed2bbedf3bbfafa89ec6691235645147 pid=<0.2288.0> [info] Converted error OAuth2.Error to 500 response
23:44:04.777 pid=<0.2170.0> [error] #PID<0.2288.0> running BorsNG.Endpoint (cowboy_protocol) terminated
Server: xxx (http)
Request: GET /auth/github/callback?code=xxx
** (exit) an exception was raised:
    ** (OAuth2.Error) Server responded with status: 401

Headers:

server: GitHub.com
date: Wed, 07 Apr 2021 23:44:04 GMT
content-type: application/json; charset=utf-8
content-length: 80
x-github-media-type: github.v3
x-ratelimit-limit: 60
x-ratelimit-remaining: 37
x-ratelimit-reset: 1617839094
x-ratelimit-used: 23
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: xxx

Body:

%{"documentation_url" => "https://docs.github.com/rest", "message" => "Bad credentials"}

        (oauth2 2.0.0) lib/oauth2/request.ex:65: OAuth2.Request.request!/6
        (bors 0.1.0) lib/github/oauth2/oauth2.ex:50: BorsNG.GitHub.OAuth2.get_user!/1
        (bors 0.1.0) lib/web/controllers/auth_controller.ex:77: BorsNG.AuthController.callback/2
        (bors 0.1.0) lib/web/controllers/auth_controller.ex:3: BorsNG.AuthController.action/2
        (bors 0.1.0) lib/web/controllers/auth_controller.ex:3: BorsNG.AuthController.phoenix_controller_pipeline/2
        (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (bors 0.1.0) lib/web/bors_ng/endpoint.ex:1: BorsNG.Endpoint.plug_builder_call/2
        (bors 0.1.0) lib/web/bors_ng/endpoint.ex:1: BorsNG.Endpoint.call/2
```

Any help determining what might be the issue here would be great! Happy to provide more logs/debug information as needed.

**Comment by RetWolf** [comment]
The issue ended up being with a newline at the end of one of our secrets 😄  go figure. This log had me chasing all the wrong directions. For future users running into this issue, make sure there are no newlines at the end of your secrets!
