### ISSUE TITLE
SyncerInstallation error

### ISSUE THREAD

**Issue by tsvietOK** [bors-ng/bors-ng#1362]
As I understand this error appears when bors does nothing and starts syncing installations.
```
10/19/2021, 8:05:17.830 AM	Informational	08:05:17.824 pid=<0.3033.0> [error] Task #PID<0.3033.0> started from #PID<0.3031.0> terminating			
10/19/2021, 8:05:17.830 AM	Informational	** (MatchError) no match of right hand side value: {:error, {:already_registered, #PID<0.3029.0>}​}			
10/19/2021, 8:05:17.830 AM	Informational	(bors 0.1.0) lib/worker/syncer_installation.ex:60: BorsNG.Worker.SyncerInstallation.synchronize_installation/1			
10/19/2021, 8:05:17.830 AM	Informational	(elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2			
10/19/2021, 8:05:17.830 AM	Informational	(stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3			
10/19/2021, 8:05:17.830 AM	Informational	Function: #Function<5.74509085/0 in BorsNG.Worker.SyncerInstallation.start_synchronize_installation/1>			
10/19/2021, 8:05:17.830 AM	Informational	Args: []
```

**Comment by unicolet** [comment]
we're having this error when we try to add a new repo to a private bors instance: the outcome is that the repo does not get added to bors (it does not show up in the projects table), while it appears as added in the GH app page

it's happening out of the blue, as the bors instance has been working flawlessly so far, and we also added other repos in the past few months

we're added and removed the repo a few times so far, and still we cannot get it to work. We inspected the GH payload sent to bors and they (to our untrained eyes) appear to be ok
