### ISSUE TITLE
BorsNG.Endpoint terminated: constraint error when attempting to insert struct

### ISSUE THREAD

**Issue by tsvietOK** [bors-ng/bors-ng#1380]
```
2021-11-02T14:46:44.216462549Z: [INFO]  14:46:44.215 request_id=FrPCAiVdjFohFbIAAKZh pid=<0.7694.0> [info] WebhookController: Got unknown action: review_requested
2021-11-02T14:46:44.216524249Z: [INFO]  14:46:44.215 request_id=FrPCAiVdjFohFbIAAKZh pid=<0.7694.0> [info] Sent 200 in 76ms
2021-11-02T14:46:44.221864820Z: [INFO]  14:46:44.220 request_id=FrPCAieqpEBODkwAAKZx pid=<0.7695.0> [info] Sent 500 in 43ms
2021-11-02T14:46:44.221909020Z: [INFO]  14:46:44.221 pid=<0.2088.0> [error] #PID<0.7695.0> running BorsNG.Endpoint (cowboy_protocol) terminated
2021-11-02T14:46:44.221914920Z: [INFO]  Server: <server-name>:80 (http)
2021-11-02T14:46:44.221936720Z: [INFO]  Request: POST /webhook/github
2021-11-02T14:46:44.221940920Z: [INFO]  ** (exit) an exception was raised:
2021-11-02T14:46:44.221944920Z: [INFO]      ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
2021-11-02T14:46:44.221949020Z: [INFO]  
2021-11-02T14:46:44.221952620Z: [INFO]      * patches_pr_xref_index (unique_constraint)
2021-11-02T14:46:44.221963320Z: [INFO]  
2021-11-02T14:46:44.221967920Z: [INFO]  If you would like to stop this constraint violation from raising an
2021-11-02T14:46:44.221987820Z: [INFO]  exception and instead add it as an error to your changeset, please
2021-11-02T14:46:44.221991420Z: [INFO]  call `unique_constraint/3` on your changeset with the constraint
2021-11-02T14:46:44.222004019Z: [INFO]  `:name` as an option.
2021-11-02T14:46:44.222007919Z: [INFO]  
2021-11-02T14:46:44.222011019Z: [INFO]  The changeset has not defined any constraint.
2021-11-02T14:46:44.222014319Z: [INFO]  
2021-11-02T14:46:44.222017319Z: [INFO]          (ecto 3.7.1) lib/ecto/repo/schema.ex:783: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
2021-11-02T14:46:44.222020819Z: [INFO]          (elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
2021-11-02T14:46:44.222024219Z: [INFO]          (ecto 3.7.1) lib/ecto/repo/schema.ex:768: Ecto.Repo.Schema.constraints_to_errors/3
2021-11-02T14:46:44.222027519Z: [INFO]          (ecto 3.7.1) lib/ecto/repo/schema.ex:749: Ecto.Repo.Schema.apply/4
2021-11-02T14:46:44.222030819Z: [INFO]          (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
2021-11-02T14:46:44.222034219Z: [INFO]          (ecto 3.7.1) lib/ecto/repo/schema.ex:985: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
2021-11-02T14:46:44.222037519Z: [INFO]          (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:1013: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
2021-11-02T14:46:44.222050419Z: [INFO]          (db_connection 2.4.0) lib/db_connection.ex:1512: DBConnection.run_transaction/4
2021-11-02T14:46:44.356729197Z: [INFO]  14:46:44.356 request_id=FrPCAjJgR3LvgZwAAKaB pid=<0.7696.0> [info] POST /webhook/github
```

**Comment by t0yv0** [comment]
https://app.bors.tech/repositories/47808/log#batch-282189

```

{%Ecto.ConstraintError{
   type: :unique,
   constraint: "statuses_identifier_batch_id_index",
   message: "constraint error when attempting to insert struct:\n\n    * statuses_identifier_batch_id_index (unique_constraint)\n\nIf you would like to stop this constraint violation from raising an\nexception and instead add it as an error to your changeset, please\ncall `unique_constraint/3` on your changeset with the constraint\n`:name` as an option.\n\nThe changeset has not defined any constraint.\n"
 },
 [
   {Ecto.Repo.Schema, :"-constraints_to_errors/3-fun-1-", 4,
    [file: 'lib/ecto/repo/schema.ex', line: 795]},
   {Enum, :"-map/2-lists^map/1-0-", 2,
    [file: 'lib/enum.ex', line: 1658]},
   {Ecto.Repo.Schema, :constraints_to_errors, 3,
    [file: 'lib/ecto/repo/schema.ex', line: 780]},
   {Ecto.Repo.Schema, :apply, 4,
    [file: 'lib/ecto/repo/schema.ex', line: 761]},
   {Ecto.Repo.Schema, :"-do_insert/4-fun-3-", 15,
    [file: 'lib/ecto/repo/schema.ex', line: 369]},
   {Ecto.Repo.Schema, :insert!, 4,
    [file: 'lib/ecto/repo/schema.ex', line: 265]},
   {Enum, :"-each/2-lists^foreach/1-0-", 2,
    [file: 'lib/enum.ex', line: 975]},
   {BorsNG.Worker.Batcher, :setup_statuses, 2,
    [file: 'lib/worker/batcher.ex', line: 655]}
 ]}

```
