### ISSUE TITLE
Authentication token caching

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#148]
Hi! I've enabled bors-ng on intellij-rust today, and while it have merged a couple of pull requests successfully, it seem to have missed the `r+` on this one:

https://github.com/intellij-rust/intellij-rust/pull/1130

![even robots ingnore me](https://cloud.githubusercontent.com/assets/1711539/24871250/ad1f53e4-1e21-11e7-8add-e9a6488579bb.png)

**Comment by notriddle** [comment]
```
2017-04-10T16:04:19.897561+00:00 app[web.1]: 16:04:19.897 [error] #PID<0.11691.0> running BorsNG.Endpoint terminated
2017-04-10T16:04:19.897563+00:00 app[web.1]: Server: bors-app.herokuapp.com:80 (http)
2017-04-10T16:04:19.897564+00:00 app[web.1]: Request: POST /webhook/github
2017-04-10T16:04:19.897564+00:00 app[web.1]: ** (exit) an exception was raised:
2017-04-10T16:04:19.897565+00:00 app[web.1]:     ** (MatchError) no match of right hand side value: {:error, :get_pr, 401, 1130}
2017-04-10T16:04:19.897566+00:00 app[web.1]:         (bors_github) lib/github.ex:27: BorsNG.GitHub.get_pr!/2
2017-04-10T16:04:19.897566+00:00 app[web.1]:         (bors_frontend) web/command.ex:65: BorsNG.Command.fetch_pr/1
2017-04-10T16:04:19.897567+00:00 app[web.1]:         (bors_frontend) web/command.ex:199: BorsNG.Command.run/3
2017-04-10T16:04:19.897567+00:00 app[web.1]:         (bors_frontend) web/controllers/webhook_controller.ex:82: BorsNG.WebhookController.webhook/2
2017-04-10T16:04:19.897568+00:00 app[web.1]:         (bors_frontend) web/controllers/webhook_controller.ex:1: BorsNG.WebhookController.action/2
2017-04-10T16:04:19.897569+00:00 app[web.1]:         (bors_frontend) web/controllers/webhook_controller.ex:1: BorsNG.WebhookController.phoenix_controller_pipeline/2
2017-04-10T16:04:19.897569+00:00 app[web.1]:         (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.instrument/4
2017-04-10T16:04:19.897570+00:00 app[web.1]:         (bors_frontend) lib/phoenix/router.ex:261: BorsNG.Router.dispatch/2
```

This looks like the corresponding log (1130 is the PR number). According to the log, GitHub returned a 403 error to bors for some reason.

**Comment by notriddle** [comment]
More detailed error log (harvested by trying to sync PRs):

```
2017-04-10T16:36:48.578795+00:00 app[web.1]: 16:36:48.578 [error] Task #PID<0.11781.0> started from #PID<0.11780.0> terminating
2017-04-10T16:36:48.578801+00:00 app[web.1]: ** (stop) exited in: GenServer.call(BorsNG.GitHub, {:get_open_prs, {{:installation, 19653}, 42619487}, {}}, 5000)
2017-04-10T16:36:48.578803+00:00 app[web.1]:     ** (EXIT) an exception was raised:
2017-04-10T16:36:48.578805+00:00 app[web.1]:         ** (MatchError) no match of right hand side value: %HTTPoison.Response{body: "{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github
.com/v3\"}", headers: [{"Server", "GitHub.com"}, {"Date", "Mon, 10 Apr 2017 16:36:48 GMT"}, {"Content-Type", "application/json; charset=utf-8"}, {"Content-Length", "83"}, {"Status", "401 Unauthorized"}, {"X-GitHu
b-Media-Type", "github.v3; format=json"}, {"X-RateLimit-Limit", "60"}, {"X-RateLimit-Remaining", "57"}, {"X-RateLimit-Reset", "1491843291"}, {"Access-Control-Expose-Headers", "ETag, Link, X-GitHub-OTP, X-RateLimi
t-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval"}, {"Access-Control-Allow-Origin", "*"}, {"Content-Security-Policy", "default-src 'none'"}, {"Strict-Tra
nsport-Security", "max-age=31536000; includeSubdomains; preload"}, {"X-Content-Type-Options", "nosniff"}, {"X-Frame-Options", "deny"}, {"X-XSS-Protection", "1; mode=block"}, {"X-GitHub-Request-Id", "E4DE:2AB54:91
1E:B8E4:58EBB4A0"}], status_code: 401}
2017-04-10T16:36:48.578806+00:00 app[web.1]:             (bors_github) lib/github/server.ex:300: BorsNG.GitHub.Server.get_open_prs_!/3
2017-04-10T16:36:48.578807+00:00 app[web.1]:             (bors_github) lib/github/server.ex:66: BorsNG.GitHub.Server.do_handle_call/3
2017-04-10T16:36:48.578809+00:00 app[web.1]:             (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
2017-04-10T16:36:48.578808+00:00 app[web.1]:             (bors_github) lib/github/server.ex:43: BorsNG.GitHub.Server.handle_call/3
2017-04-10T16:36:48.578809+00:00 app[web.1]:             (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
2017-04-10T16:36:48.578810+00:00 app[web.1]:             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2017-04-10T16:36:48.578811+00:00 app[web.1]:     (elixir) lib/gen_server.ex:737: GenServer.call/3
2017-04-10T16:36:48.578812+00:00 app[web.1]:     (bors_github) lib/github.ex:33: BorsNG.GitHub.get_open_prs!/1
2017-04-10T16:36:48.578812+00:00 app[web.1]:     (bors_frontend) lib/bors_ng/syncer.ex:25: BorsNG.Syncer.synchronize_project/1
2017-04-10T16:36:48.578813+00:00 app[web.1]:     (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
2017-04-10T16:36:48.578814+00:00 app[web.1]: Function: #Function<0.97365269/0 in BorsNG.Syncer.start_synchronize_project/1>
2017-04-10T16:36:48.578814+00:00 app[web.1]:     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2017-04-10T16:36:48.578816+00:00 app[web.1]:     Args: []
```

I just cleared the credentials cache, and syncing PRs doesn't error out. I'll keep this issue open, to track any repeats of this bug. ☹️

**Comment by matklad** [comment]
Integration is enabled though: 

![integration](https://cloud.githubusercontent.com/assets/1711539/24872235/605f5a78-1e25-11e7-85ac-57cd190c3cdc.png)

I'll try other pull requests tomorrow.

**Comment by notriddle** [comment]
I cleared the credentials cache. That seems to have fixed the problem.
