### ISSUE TITLE
Crash in batcher

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#45]
```
[error] GenServer Aelita2.Batcher terminating
** (BadMapError) expected a map, got: [{"continuous-integration/codeship", 2}]
   (stdlib) :maps.is_key("continuous-integration/codeship", [{"continuous-integration/codeship", 2}])
   (aelita2) lib/aelita2/batcher.ex:216: anonymous fn/2 in Aelita2.Batcher.poll_running_batch/1
   (elixir) lib/enum.ex:814: anonymous fn/3 in Enum.filter/2
   (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
   (elixir) lib/enum.ex:814: Enum.filter/2
   (aelita2) lib/aelita2/batcher.ex:216: Aelita2.Batcher.poll_running_batch/1
   (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
   (elixir) lib/enum.ex:645: Enum.each/2
```

After bors got its first PR which was ready to be merged (all statuses green), it started crashing with this message.
The bors.toml for this project looks like:

```
status = [
          "continuous-integration/codeship",
          "nubis/accepted"]
```

I can't get bors up again, it keeps crashing with this message on startup.

**Comment by notriddle** [comment]
That should have fixed it.

**Comment by timvdalen** [comment]
Yes, this crash is fixed.

I'll let you know if I run into any more issues.

**Comment by notriddle** [comment]
Thanks!
