### ISSUE TITLE
Branches sometimes don't get deleted

### ISSUE THREAD

**Issue by andschwa** [bors-ng/bors-ng#525]
We're getting occasional crashes when Bors tries to delete a merged branch:

```
01:29:12.114 [error] GenServer BorsNG.Worker.BranchDeleter terminating
** (MatchError) no match of right hand side value: {:error, :delete_branch}
    (bors) lib/github/github.ex:78: BorsNG.GitHub.delete_branch!/2
    (bors) lib/worker/branch_deleter.ex:45: BorsNG.Worker.BranchDeleter.handle_cast/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:delete, %BorsNG.Database.Patch{__meta__: #Ecto.Schema.Metadata<:loaded, "patches">, author: #Ecto.Association.NotLoaded<association :author is not loaded>, author_id: 78, body: "Libcxx library updated to 7.0. Updated tests list found in [f9
5e20](https://github.com/Microsoft/openenclave/commit/f95e20ef222be9b27ac6b6ab8f84516942af7282)\r\ntests.all - 5393\r\ntest.supported - 4668\r\ntests.unsupported - 709\r\ntests.broken - 16\r\n", commit: "5a58abf4b7931f71f9e1617101bad45c692ecc44", id: 116, inserted_at: ~N
[2018-10-04 12:10:55.060688], into_branch: "master", open: false, pr_xref: 826, priority: 0, project: #Ecto.Association.NotLoaded<association :project is not loaded>, project_id: 3, title: "Feature/libcxx update #701", updated_at: ~N[2018-10-24 01:29:11.547144]}, 0}}

=CRASH REPORT==== 24-Oct-2018::01:29:12 ===
  crasher:
    initial call: Elixir.BorsNG.Worker.BranchDeleter:init/1
    pid: <0.1767.0>
    registered_name: 'Elixir.BorsNG.Worker.BranchDeleter'
    exception exit: {{badmatch,{error,delete_branch}},
                     [{'Elixir.BorsNG.GitHub','delete_branch!',2,
                          [{file,"lib/github/github.ex"},{line,78}]},
                      {'Elixir.BorsNG.Worker.BranchDeleter',handle_cast,2,
                          [{file,"lib/worker/branch_deleter.ex"},{line,45}]},
                      {gen_server,try_dispatch,4,
                          [{file,"gen_server.erl"},{line,601}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,667}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 812)
    ancestors: ['Elixir.BorsNG.Supervisor',<0.1733.0>]
    messages: []
    links: [<0.1734.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 14914
  neighbours:
```

This was for https://github.com/Microsoft/openenclave/pull/826

The branch had to be manually deleted instead.

**Comment by andschwa** [comment]
There's been no movement on this issue for two years, and since I opened it, I'm going to close it 😉
