### ISSUE TITLE
The Access calls for keywords expect the key to be an atom

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#55]
Got a crash in Access:

```
** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: 0
    (elixir) lib/access.ex:255: Access.fetch/2
    (elixir) lib/access.ex:269: Access.get/3
    (aelita2) lib/aelita2/batcher.ex:268: Aelita2.Batcher.bisect/1
    (aelita2) lib/aelita2/batcher.ex:256: Aelita2.Batcher.maybe_complete_batch/3
    (aelita2) lib/aelita2/batcher.ex:227: Aelita2.Batcher.maybe_complete_batch/1
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
```

Do you need any more data?
This was after three staging.tmp builds failed.

**Comment by notriddle** [comment]
staging.tmp builds are completely ignored by Bors. Only staging itself matters.

**Comment by timvdalen** [comment]
That one broke as well

**Comment by notriddle** [comment]
I shouldn't need any more data, no.

**Comment by timvdalen** [comment]
Fixed!
