### ISSUE TITLE
Configurable GenServer timeouts

### ISSUE THREAD

**Issue by tr-argo** [bors-ng/bors-ng#579]
I'm currently running into issues where a batch crashes when the `get_commit_status` for one of the PR takes longer then 5 seconds. During this failure, the entire bash crashes and the remaining PR's are not re-queued. I'm investigating why the API calls are taking almost 5 seconds, but is it possible for GenServer timeout to be configurable? 

 ```
** (stop) exited in: GenServer.call(BorsNG.GitHub, {:get_commit_status, {{:installation, 16}, 32}, {"<sha>"}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (bors) lib/github/github.ex:120: BorsNG.GitHub.get_commit_status!/2
    (bors) lib/worker/batcher.ex:346: BorsNG.Worker.Batcher.poll_running_batch/1
    (bors) lib/worker/batcher.ex:194: BorsNG.Worker.Batcher.poll/1
    (bors) lib/worker/batcher.ex:176: BorsNG.Worker.Batcher.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:poll, :repeat}
```

```
18:35:34.563 [error] GenServer #PID<0.15774.203> terminating
** (stop) exited in: GenServer.call(BorsNG.GitHub, {:post_commit_status, {{:installation, 16}, 32}, {"<sha>", :error, "Canceled", "<url>#batch-1149"}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (bors) lib/github/github.ex:160: BorsNG.GitHub.post_commit_status!/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (bors) lib/worker/batcher.ex:582: BorsNG.Worker.Batcher.send_status/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (bors) lib/worker/batcher.ex:168: BorsNG.Worker.Batcher.do_handle_cast/2
Last message: {:"$gen_cast", {:cancel_all}}
```

**Comment by notriddle** [comment]
It's not supported right now, but sure, if someone wants to make the GitHub API call timeouts configurable, I wouldn't reject a pull request.
