### ISSUE TITLE
Two PRs on 'Running' (Retrying)

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#59]
The currently 'Running' batch has two PRs in it, both of which have failed before.
Bors made a comment:

>Build failed (retrying...)
>
>continuous-integration/codeship

But nothing else is happening.
The PRs have since been fixed and are green, and I have commented `bors r+` again.

What should trigger the retry?

bors has made no new commits to staging or staging.tmp and I see nothing in the logs related to this.

**Comment by timvdalen** [comment]
Closing and opening the PRs made this show up in the logs:

```
[error] GenServer Aelita2.Batcher terminating
** (Ecto.NoResultsError) expected at least one result but got none in query:
** (Ecto.NoResultsError) expected at least one result but got none in query:
from p in Aelita2.Patch,
from p in Aelita2.Patch,
  left_join: l in subquery(from l in Aelita2.LinkPatchBatch,
  left_join: l in subquery(from l in Aelita2.LinkPatchBatch,
  join: b in Aelita2.Batch,
  join: b in Aelita2.Batch,
  on: l.batch_id == b.id and b.state != ^3),
  on: l.batch_id == b.id and b.state != ^3),
  on: l.patch_id == p.id,
  on: l.patch_id == p.id,
  where: is_nil(l.batch_id),
  where: p.open,
  where: p.id == ^6
    (ecto) lib/ecto/repo/queryable.ex:74: Ecto.Repo.Queryable.one!/4
  where: is_nil(l.batch_id),
  where: p.open,
    (aelita2) lib/aelita2/batcher.ex:63: Aelita2.Batcher.do_handle_cast/1
  where: p.id == ^6
    (ecto) lib/ecto/repo/queryable.ex:74: Ecto.Repo.Queryable.one!/4
    (aelita2) lib/aelita2/batcher.ex:63: Aelita2.Batcher.do_handle_cast/1
    (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
    (aelita2) lib/aelita2/batcher.ex:58: Aelita2.Batcher.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
Last message: {:"$gen_cast", {:reviewed, 6}}
    (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
    (aelita2) lib/aelita2/batcher.ex:58: Aelita2.Batcher.handle_cast/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
Last message: {:"$gen_cast", {:reviewed, 6}}
```

(I'm guessing this is two sets of logs interleaved, though I'm only running one process)

**Comment by notriddle** [comment]
It's normal for two PRs to run at once. That's how batching works.

**Comment by notriddle** [comment]
CC #25

**Comment by notriddle** [comment]
I haven't managed to reproduce this bug, but I have added the ability to cancel PRs (with PR #63).

Your problem might be #61, but I'm not sure of that.

**Comment by timvdalen** [comment]
Yes, things are moving again!
