### ISSUE TITLE
Permissions "Sync" not working/timing out

### ISSUE THREAD

**Issue by vvuk** [bors-ng/bors-ng#608]
I have a bors instance running on heroku connected to a private repository.  Both the github app and the repo are in a github org.

Bors' permissions sync doesn't seem to be working -- I'd like to give everyone who can pull the repo access to review and try, so I set the permissions to "Pull" and hit Update.  But it doesn't take; in the web logs I see:

```
2019-02-23T20:15:46.562766+00:00 app[web.1]: 20:15:46.562 [error] Task #PID<0.2526.0> started from #PID<0.2525.0> terminating
2019-02-23T20:15:46.562784+00:00 app[web.1]: ** (stop) exited in: GenServer.call(BorsNG.GitHub, {:get_collaborators_by_repo, {{:installation, xxxx}, yyyy}, {}}, 10000)
2019-02-23T20:15:46.562788+00:00 app[web.1]:     ** (EXIT) time out
2019-02-23T20:15:46.562790+00:00 app[web.1]:     (elixir) lib/gen_server.ex:924: GenServer.call/3
2019-02-23T20:15:46.562792+00:00 app[web.1]:     (bors) lib/worker/syncer.ex:75: BorsNG.Worker.Syncer.synchronize_project_collaborators/2
2019-02-23T20:15:46.562794+00:00 app[web.1]:     (bors) lib/worker/syncer.ex:39: BorsNG.Worker.Syncer.synchronize_project/1
2019-02-23T20:15:46.562797+00:00 app[web.1]:     (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
2019-02-23T20:15:46.562799+00:00 app[web.1]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
2019-02-23T20:15:46.562800+00:00 app[web.1]: Function: #Function<0.123068736/0 in BorsNG.Worker.Syncer.start_synchronize_project/1>
2019-02-23T20:15:46.562802+00:00 app[web.1]:     Args: []
```

There are around 2000 members in case this matters.

**Comment by vvuk** [comment]
Aaand that was it.  Bumping this to 60000 fixed it.  (I think git only needed ~15s but still.)  Sorry for noise!

**Comment by vvuk** [comment]
GITHUB_API_TIMEOUT is the default 10_000.
