### ISSUE TITLE
Crash after reviewing

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#75]
```
Request: POST /webhook/github
** (exit) an exception was raised:
** (CaseClauseError) no case clause matching: {{0, 7}, :nomatch}
   (aelita2) web/controllers/webhook_controller.ex:215: Aelita2.WebhookController.do_webhook_comment/2
   (aelita2) web/controllers/webhook_controller.ex:23: Aelita2.WebhookController.webhook/2
   (aelita2) web/controllers/webhook_controller.ex:1: Aelita2.WebhookController.action/2
   (aelita2) web/controllers/webhook_controller.ex:1: Aelita2.WebhookController.phoenix_controller_pipeline/2
   (aelita2) lib/aelita2/endpoint.ex:1: Aelita2.Endpoint.instrument/4
   (aelita2) lib/phoenix/router.ex:261: Aelita2.Router.dispatch/2
   (aelita2) web/router.ex:1: Aelita2.Router.do_call/2
   (aelita2) lib/aelita2/endpoint.ex:1: Aelita2.Endpoint.phoenix_pipeline/1

```

**Comment by notriddle** [comment]
Is that PR linked to a branch other than master?

**Comment by timvdalen** [comment]
Yes, I hadn't even noticed.
In this case it's from master to the release branch.

I wouldn't mind bors just ignoring this PR then, but in that case it should also not show up on the dashboard.

**Comment by notriddle** [comment]
I fixed this awhile back (in https://github.com/bors-ng/bors-ng/pull/171).
