### ISSUE TITLE
constraint error when synchronizing users: unique: users_login_index

### ISSUE THREAD

**Issue by vvuk** [bors-ng/bors-ng#769]
When I attempt to synchronize all reviewers with "Push" permission, I get:

```
2019-10-11T18:21:24.351112+00:00 app[web.1]: ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
2019-10-11T18:21:24.351115+00:00 app[web.1]: 
2019-10-11T18:21:24.351118+00:00 app[web.1]:     * unique: users_login_index
2019-10-11T18:21:24.351120+00:00 app[web.1]: 
2019-10-11T18:21:24.351122+00:00 app[web.1]: If you would like to convert this constraint into an error, please
2019-10-11T18:21:24.351124+00:00 app[web.1]: call unique_constraint/3 in your changeset and define the proper
2019-10-11T18:21:24.351127+00:00 app[web.1]: constraint name. The changeset has not defined any constraint.
2019-10-11T18:21:24.351129+00:00 app[web.1]: 
2019-10-11T18:21:24.351132+00:00 app[web.1]:     (ecto) lib/ecto/repo/schema.ex:574: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
2019-10-11T18:21:24.351134+00:00 app[web.1]:     (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
2019-10-11T18:21:24.351138+00:00 app[web.1]:     (ecto) lib/ecto/repo/schema.ex:559: Ecto.Repo.Schema.constraints_to_errors/3
2019-10-11T18:21:24.351140+00:00 app[web.1]:     (ecto) lib/ecto/repo/schema.ex:222: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
2019-10-11T18:21:24.351142+00:00 app[web.1]:     (ecto) lib/ecto/repo/schema.ex:774: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
2019-10-11T18:21:24.351144+00:00 app[web.1]:     (db_connection) lib/db_connection.ex:1374: DBConnection.transaction_nested/2
2019-10-11T18:21:24.351147+00:00 app[web.1]:     (db_connection) lib/db_connection.ex:1234: DBConnection.transaction_meter/3
2019-10-11T18:21:24.351149+00:00 app[web.1]:     (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
2019-10-11T18:21:24.351151+00:00 app[web.1]: Function: #Function<0.123068736/0 in BorsNG.Worker.Syncer.start_synchronize_project/1>
2019-10-11T18:21:24.351153+00:00 app[web.1]:     Args: []
```

I can synchronize "Admin" permission without problems.  Not sure where to even start debugging.  I am an admin of the project; not sure if it's intended but my github username always shows up in the Reviewers column without the ability to remove it (even when "None" is selected for sync)  (Ah, I guess admins are always users).

**Comment by vvuk** [comment]
I've manually cleared out `link_member_project` and `link_user_project` tables for this project; the error still occurs.  There are a few hundred people with "Push" access; I've upped the github API timeout already.

**Comment by vvuk** [comment]
I'm learning so much about elixir :)  So after putting in a bunch of logging.  What seems to have happened is there was a user with name "Foo" who had github user id "100".  Now "Foo" has github user id "200", which I can guess happened because original "Foo" changed their username, and then created a new "Foo".
