### ISSUE TITLE
no function clause matching in anonymous fn/2 in BorsNG.GitHub.Reviews.from_json!/1

### ISSUE THREAD

**Issue by zegl** [bors-ng/bors-ng#792]
We currently have a PR that produces the following crash when someone comments with "bors r+", for this particular PR it's reproducible, and happens every time someone adds a r+ comment.

Log extract:

```
13:50:38.218 request_id=FdU0MsrDnACX1MkAAA5i [info] Sent 200 in 627ms
13:50:38.547 request_id=FdU0MwPOjoC9AiYAAAix [info] POST /webhook/github
13:50:38.551 request_id=FdU0MwPOjoC9AiYAAAix [info] Sent 200 in 3ms
13:50:38.759 request_id=FdU0MxBqGfm9AiYAAAjR [info] POST /webhook/github
13:50:38.759 request_id=FdU0MxBqGfm9AiYAAAjR [info] POST /webhook/github
13:50:38.761 request_id=FdU0MxBqGfm9AiYAAAjR [info] Sent 200 in 1ms
13:50:38.823 [error] GenServer BorsNG.GitHub terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in BorsNG.GitHub.Reviews.from_json!/1
(bors) lib/github/github/reviews.ex:14: anonymous fn(%{"_links" => %{"html" => %{"href" => "https://github.com/[[ CENSORED ]]#pullrequestreview-[[ CENSORED ]]"}, "pull_request" => %{"href" => "https://api.github.com/repos/[[ CENSORED ]]/pulls/[[ CENSORED ]]"}}, "author_association" => "NONE", "body" => "", "commit_id" => "fd2031b40b7dda2a1
(elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
(bors) lib/github/github/reviews.ex:14: BorsNG.GitHub.Reviews.from_json!/1
(bors) lib/github/github/server.ex:289: BorsNG.GitHub.Server.do_handle_call/3
(bors) lib/github/github/server.ex:618: BorsNG.GitHub.Server.use_token!/3
(stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
(stdlib) gen_server.erl:690: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.2297.0>): {:get_reviews, {{:installation, [[ CENSORED ]]}, [[ CENSORED ]]}, {[[ CENSORED ]]}}
13:50:38.824 [error] GenServer #PID<0.2297.0> terminating
** (stop) exited in: GenServer.call(BorsNG.GitHub, {:get_reviews, {{:installation, [[ CENSORED ]]}, [[ CENSORED ]]}, {[[ CENSORED ]]}}, 10000)
** (EXIT) an exception was raised:
** (FunctionClauseError) no function clause matching in anonymous fn/2 in BorsNG.GitHub.Reviews.from_json!/1
(bors) lib/github/github/reviews.ex:14: anonymous fn(%{"_links" => %{"html" => %{"href" => "https://github.com/[[ CENSORED ]]#pullrequestreview-[[ CENSORED ]]"}, "pull_request" => %{"href" => "https://api.github.com/repos/[[ CENSORED ]]/pulls/[[ CENSORED ]]"}}, "author_association" => "NONE", "body" => "", "commit_id" => "fd2031b40
(elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
(bors) lib/github/github/reviews.ex:14: BorsNG.GitHub.Reviews.from_json!/1
(bors) lib/github/github/server.ex:289: BorsNG.GitHub.Server.do_handle_call/3
(bors) lib/github/github/server.ex:618: BorsNG.GitHub.Server.use_token!/3
(stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
(stdlib) gen_server.erl:690: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
(elixir) lib/gen_server.ex:924: GenServer.call/3
(bors) lib/github/github.ex:161: BorsNG.GitHub.get_reviews!/2
(bors) lib/worker/batcher.ex:612: BorsNG.Worker.Batcher.patch_preflight/3
(bors) lib/worker/batcher.ex:118: BorsNG.Worker.Batcher.do_handle_cast/2
(bors) lib/worker/batcher.ex:83: BorsNG.Worker.Batcher.handle_cast/2
(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:711: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:reviewed, 18261, "zegl"}}
13:50:38.933 [info] Running BorsNG.Endpoint with cowboy 1.1.2 at 0.0.0.0:4000 (http)
13:50:38.934 [info] Access BorsNG.Endpoint at [[ CENSORED ]]
13:50:40.696 [info] CONNECTED TO BorsNG.UserSocket in 1ms
Transport: :websocket
Serializer: Phoenix.Socket.V2.JSONSerializer
Connect Info: %{}
Parameters: %{"token" => "[[ CENSORED ]]", "vsn" => "2.0.0"}
13:50:40.821 [info] JOINED project_ping:92 in 1ms
Parameters: %{}
13:50:43.938 request_id=FdU0NEUhcbPppugAAAlx [info] POST /webhook/github
13:50:43.940 request_id=FdU0NEUhcbPppugAAAlx [info] Sent 200 in 2ms
13:50:44
13:50:44.007 request_id=FdU0NEk2u-_ppugAAA5y [info] POST /webhook/github
```

**Comment by dvic** [comment]
We are seeing the same problems (PR's from dependabot).
