### ISSUE TITLE
Crash after merge #839

### ISSUE THREAD

**Issue by miguelslemos** [bors-ng/bors-ng#890]
Hi! Thanks for bors-ng.

After we pull latest version from Dockerhub(c308cf16bdfc46713baf30386e9e904517b20fea) we got `CrashLoopBackOff`

```
+ exec ./bors/bin/bors foreground
Running migrations for bors
14:42:11.557 pid=<0.1772.0> [info] Application bors exited: BorsNG.Application.start(:normal, []) returned an error: shutdown: failed to start child: BorsNG.Attrs
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :get_app, %Tesla.Env{__client__: %Tesla.Client{adapter: {Tesla.Adapter.Httpc, :call, [[ssl: [verify: :verify_peer, verify_fun: {&:ssl_verify_hostname.verify_fun/3, [check_hostname: 'api.github.com']}, cacertfile: '/app/bors/lib/certifi-2.5.1/priv/cacerts.pem']]]}, fun: nil, post: [], pre: [{Tesla.Middleware.BaseUrl, :call, ["https://api.github.com"]}, {Tesla.Middleware.Headers, :call, [[{"authorization", "Bearer *"}, {"accept", "application/vnd.github.machine-man-preview+json"}, {"user-agent", "bors-ng https://bors.tech"}]]}, {Tesla.Middleware.Retry, :call, [[delay: 100, max_retries: 5]]}]}, __module__: Tesla, body: "", headers: [{"date", "Thu, 27 Feb 2020 14:42:11 GMT"}, {"server", "GitHub.com"}, {"vary", "Accept-Encoding, Accept, X-Requested-With"}, {"content-length", "0"}, {"x-github-request-id", "28EB:0C52:21DFEB:51876E:5E57D541"}], method: :get, opts: [], query: [], status: 500, url: "https://api.github.com/app"}}
            (bors) lib/github/github.ex:273: BorsNG.GitHub.get_app!/0
            (bors) lib/github/attrs.ex:11: BorsNG.Attrs.start_link/0
            (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
            (stdlib) supervisor.erl:1157: :supervisor.children_map/4
            (stdlib) supervisor.erl:315: :supervisor.init_children/2
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
{"Kernel pid terminated",application_controller,"{application_start_failure,bors,{{shutdown,{failed_to_start_child,'Elixir.BorsNG.Attrs',{'EXIT',{{badmatch,{error,get_app,#{'__client__' => #{'__struct__' => 'Elixir.Tesla.Client',adapter => {'Elixir.Tesla.Adapter.Httpc',call,[[{ssl,[{verify,verify_peer},{verify_fun,{fun ssl_verify_hostname:verify_fun/3,[{check_hostname,\"api.github.com\"}]}},{cacertfile,\"/app/bors/lib/certifi-2.5.1/priv/cacerts.pem\"}]}]]},'fun' => nil,post => [],pre => [{'Elixir.Tesla.Middleware.BaseUrl',call,[<<\"https://api.github.com\">>]},{'Elixir.Tesla.Middleware.Headers',call,[[{<<\"authorization\">>,<<\"Bearer *\">>},{<<\"accept\">>,<<\"application/vnd.github.machine-man-preview+json\">>},{<<\"user-agent\">>,<<\"bors-ng https://bors.tech\">>}]]},{'Elixir.Tesla.Middleware.Retry',call,[[{delay,100},{max_retries,5}]]}]},'__module__' => 'Elixir.Tesla','__struct__' => 'Elixir.Tesla.Env',body => <<>>,headers => [{<<\"date\">>,<<\"Thu, 27 Feb 2020 14:42:11 GMT\">>},{<<\"server\">>,<<\"GitHub.com\">>},{<<\"vary\">>,<<\"Accept-Encoding, Accept, X-Requested-With\">>},{<<\"content-length\">>,<<\"0\">>},{<<\"x-github-request-id\">>,<<\"28EB:0C52:21DFEB:51876E:5E57D541\">>}],method => get,opts => [],query => [],status => 500,url => <<\"https://api.github.com/app\">>}}},[{'Elixir.BorsNG.GitHub','get_app!',0,[{file,\"lib/github/github.ex\"},{line,273}]},{'Elixir.BorsNG.Attrs',start_link,0,[{file,\"lib/github/attrs.ex\"},{line,11}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,379}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,349}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1157}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,315}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]}]}}}},{'Elixir.BorsNG.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,bors,{{shutdown,{failed_to_start_child,'Elixir.BorsNG.Attrs',{'EXIT',{{badmatch,{error,get_app,#{'__client__' => #{'__struct_
```

**Comment by notriddle** [comment]
> status: 500

That's not us. That's GitHub's own server having trouble, as described on <https://www.githubstatus.com/>.
