### ISSUE TITLE
Bors-ng throwing 500 errors with '(CaseClauseError) no case clause matching: "neutral"'

### ISSUE THREAD

**Issue by carlos-granados** [bors-ng/bors-ng#982]
I am seeing some errors in the Bors logs. This is for a build using CircleCI and squash and merge

These are the logs:
```
2020-07-01T08:50:30.741870+00:00 app[web.1]: 08:50:30.741 request_id=4aa47875-9145-4e0d-8360-53a31640f2c9 pid=<0.8140.0> [info] POST /webhook/github
2020-07-01T08:50:30.743200+00:00 app[web.1]: 08:50:30.742 request_id=4aa47875-9145-4e0d-8360-53a31640f2c9 pid=<0.8140.0> [info] Sent 500 in 1ms
2020-07-01T08:50:30.744367+00:00 app[web.1]: 08:50:30.742 request_id=4aa47875-9145-4e0d-8360-53a31640f2c9 pid=<0.8140.0> [info] Converted error {:case_clause, "neutral"} to 500 response
2020-07-01T08:50:30.744529+00:00 app[web.1]: 08:50:30.744 pid=<0.418.0> [error] #PID<0.8140.0> running BorsNG.Endpoint (cowboy_protocol) terminated
2020-07-01T08:50:30.744530+00:00 app[web.1]: Server: i6-merge-queue.herokuapp.com:80 (http)
2020-07-01T08:50:30.744531+00:00 app[web.1]: Request: POST /webhook/github
2020-07-01T08:50:30.744531+00:00 app[web.1]: ** (exit) an exception was raised:
2020-07-01T08:50:30.744532+00:00 app[web.1]: ** (CaseClauseError) no case clause matching: "neutral"
2020-07-01T08:50:30.744533+00:00 app[web.1]: (bors) lib/github/github.ex:376: BorsNG.GitHub.map_state_to_status/1
2020-07-01T08:50:30.744533+00:00 app[web.1]: (bors) lib/web/controllers/webhook_controller.ex:274: BorsNG.WebhookController.do_webhook/3
2020-07-01T08:50:30.744534+00:00 app[web.1]: (bors) lib/web/controllers/webhook_controller.ex:83: BorsNG.WebhookController.webhook/2
2020-07-01T08:50:30.744534+00:00 app[web.1]: (bors) lib/web/controllers/webhook_controller.ex:1: BorsNG.WebhookController.action/2
2020-07-01T08:50:30.744536+00:00 app[web.1]: (bors) lib/web/controllers/webhook_controller.ex:1: BorsNG.WebhookController.phoenix_controller_pipeline/2
2020-07-01T08:50:30.744536+00:00 app[web.1]: (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
2020-07-01T08:50:30.744537+00:00 app[web.1]: (bors) lib/web/bors_ng/endpoint.ex:1: BorsNG.Endpoint.plug_builder_call/2
2020-07-01T08:50:30.744537+00:00 app[web.1]: (bors) lib/web/bors_ng/endpoint.ex:1: BorsNG.Endpoint.call/2
```

**Comment by notriddle** [comment]
This is a bug in the [`WebhookController`](https://github.com/bors-ng/bors-ng/blob/f9dce726588bcb640bd8f876da12c71646b06bf4/lib/web/controllers/webhook_controller.ex#L274) handler for `check_run` events.

It's calling [`GitHub.map_state_to_status`](https://github.com/bors-ng/bors-ng/blob/b4e11a73dc41b1959d9079c2053f7a3861505e37/lib/github/github.ex#L394-L402) when it ought to be calling `map_check_to_status`.

**Comment by notriddle** [comment]
Fixed by https://github.com/bors-ng/bors-ng/pull/1094
